"use client";
import * as React from "react";
import JsBarcode from "jsbarcode";
import { Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import type { Barcode, Product, Variant } from "@/lib/types/product";

export function BarcodeLabelPrinter({ product, variants, barcodes }: { product: Product; variants: Variant[]; barcodes: Barcode[] }) {
  const [selected,setSelected]=React.useState<Set<number>>(new Set(barcodes.map((b)=>b.id))); const [size,setSize]=React.useState("50x25"); const [copies,setCopies]=React.useState(1);
  React.useEffect(()=>setSelected(new Set(barcodes.map((b)=>b.id))),[barcodes]);
  function print(){ const rows=barcodes.filter((b)=>selected.has(b.id)).flatMap((b)=>Array.from({length:copies},()=>b)); if(!rows.length)return; const labels=rows.map((b)=>{const v=variants.find((x)=>x.id===b.variantId); const canvas=document.createElement("canvas"); JsBarcode(canvas,b.barcode,{format:"CODE128",displayValue:true,height:46,width:1.6,margin:4,fontSize:12}); return `<div class="label"><strong>${escapeHtml(product.name)}</strong><small>${escapeHtml(v?.variantName??"Standard")} · ${escapeHtml(v?.sku??product.code)}</small><img src="${canvas.toDataURL()}" /></div>`;}).join(""); const [w,h]=size.split("x"); const win=window.open("","_blank","width=900,height=700"); if(!win)return; win.document.write(`<html><head><title>${escapeHtml(product.name)} labels</title><style>@page{size:${w}mm ${h}mm;margin:0}*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif}.label{width:${w}mm;height:${h}mm;padding:2mm;display:flex;flex-direction:column;align-items:center;justify-content:center;break-after:page;overflow:hidden}.label strong{font-size:10pt;max-width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.label small{font-size:7pt}.label img{max-width:100%;height:14mm;object-fit:contain}</style></head><body>${labels}<script>window.onload=()=>{window.print();window.onafterprint=()=>window.close()}</script></body></html>`); win.document.close(); }
  return <div className="rounded-xl border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h3 className="font-medium">Print barcode labels</h3><p className="text-xs text-muted-foreground">Thermal presets; choose Save as PDF in the print dialog for a PDF file.</p></div><div className="flex flex-wrap items-end gap-2"><label className="text-xs">Label size<select className="mt-1 block h-9 rounded-md border bg-background px-2" value={size} onChange={(e)=>setSize(e.target.value)}><option value="50x25">50 × 25 mm</option><option value="40x30">40 × 30 mm</option><option value="38x25">38 × 25 mm</option><option value="100x50">100 × 50 mm</option></select></label><label className="text-xs">Copies<InputNumber value={copies} onChange={setCopies}/></label><Button onClick={print}><Printer/>Print selected</Button></div></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{barcodes.map((b)=>{const v=variants.find((x)=>x.id===b.variantId);return <label key={b.id} className="flex min-h-11 items-center gap-2 rounded-lg border px-3 text-sm"><Checkbox checked={selected.has(b.id)} onCheckedChange={(value)=>setSelected((current)=>{const next=new Set(current);if(value)next.add(b.id);else next.delete(b.id);return next;})}/><span><span className="block font-medium">{v?.variantName??"Standard"}</span><span className="font-mono text-xs text-muted-foreground">{b.barcode}</span></span></label>;})}</div></div>;
}
function InputNumber({value,onChange}:{value:number;onChange:(n:number)=>void}){return <input className="mt-1 block h-9 w-20 rounded-md border bg-background px-2" type="number" min={1} max={100} value={value} onWheel={(e) => e.currentTarget.blur()} onChange={(e)=>onChange(Math.max(1,Number(e.target.value)||1))}/>}
function escapeHtml(value:string){return value.replace(/[&<>'"]/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]!));}
